# Generated by Django 4.2.11 on 2024-05-10 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(null=True, unique=True)),
                ("weather", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="IceExp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 5, 11, 0, 4, 42, 49604)
                    ),
                ),
                (
                    "temp",
                    models.DecimalField(decimal_places=2, default=31.0, max_digits=5),
                ),
                (
                    "humidity",
                    models.DecimalField(decimal_places=2, default=71, max_digits=5),
                ),
                ("thickness", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("duration", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="icymelt.material",
                    ),
                ),
                (
                    "weather_cond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="icymelt.weathercondition",
                    ),
                ),
            ],
        ),
    ]
