# Generated by Django 4.2.9 on 2024-04-08 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weather", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="IceExp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("humidity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("windspeed", models.DecimalField(decimal_places=2, max_digits=5)),
                ("thickness", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("duration", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="icymelt.material",
                    ),
                ),
                (
                    "weather_cond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="icymelt.weathercondition",
                    ),
                ),
            ],
        ),
    ]
