# Generated by Django 4.2.9 on 2024-04-18 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icymelt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iceexp",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 18, 13, 37, 40, 956254)
            ),
        ),
    ]
