# Generated by Django 4.2.11 on 2024-05-04 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icymelt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iceexp",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 4, 21, 45, 54, 291897)
            ),
        ),
    ]
