# Generated by Django 5.0.6 on 2024-05-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icymelt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iceexp',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
