# Generated by Django 4.2.11 on 2024-05-04 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icymelt", "0003_alter_iceexp_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="weathercondition",
            name="code",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="iceexp",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 4, 10, 18, 36, 489352)
            ),
        ),
        migrations.AlterField(
            model_name="weathercondition",
            name="weather",
            field=models.CharField(max_length=100),
        ),
    ]
