# Generated by Django 4.2.11 on 2024-05-04 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icymelt", "0004_alter_iceexp_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iceexp",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 4, 21, 49, 51, 434049)
            ),
        ),
        migrations.AlterField(
            model_name="iceexp",
            name="duration",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
